name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with: 
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
      - run: npm uninstall -g bats